"""Add description to registration_lists

Revision ID: 0c793f62dca1
Revises: 8a7a05ba5484
Create Date: 2026-04-13 21:51:38.601713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c793f62dca1'
down_revision: Union[str, None] = '8a7a05ba5484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_lists', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_lists', 'description')
    # ### end Alembic commands ###
