"""add_created_by_lecturer_to_lecturer_registrations

Revision ID: 1bace05c5e1f
Revises: 91b03dbb4837
Create Date: 2026-05-22 02:41:40.762986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bace05c5e1f'
down_revision: Union[str, None] = '91b03dbb4837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer_registrations', sa.Column('created_by_lecturer', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturer_registrations', 'created_by_lecturer')
    # ### end Alembic commands ###
