"""Add scheduling session models

Revision ID: 222d5fccf47d
Revises: 3be9a23b6c85
Create Date: 2026-04-16 00:37:32.821858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222d5fccf47d'
down_revision: Union[str, None] = '3be9a23b6c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduling_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_list_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_list_id'], ['registration_lists.list_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_sessions_id'), 'scheduling_sessions', ['id'], unique=False)
    op.create_table('session_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('major_code', sa.String(length=20), nullable=False),
    sa.Column('batch_code', sa.String(length=10), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.Column('num_classes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scheduling_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_entries_id'), 'session_entries', ['id'], unique=False)
    op.create_table('timetable_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=30), nullable=False),
    sa.Column('shift', sa.String(length=10), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('theory_hours', sa.Integer(), nullable=True),
    sa.Column('practice_hours', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('lecturer_name', sa.String(length=200), nullable=True),
    sa.Column('practice_lecturer_name', sa.String(length=200), nullable=True),
    sa.Column('day_morning', sa.String(length=10), nullable=True),
    sa.Column('day_afternoon', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scheduling_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_rows_id'), 'timetable_rows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_rows_id'), table_name='timetable_rows')
    op.drop_table('timetable_rows')
    op.drop_index(op.f('ix_session_entries_id'), table_name='session_entries')
    op.drop_table('session_entries')
    op.drop_index(op.f('ix_scheduling_sessions_id'), table_name='scheduling_sessions')
    op.drop_table('scheduling_sessions')
    # ### end Alembic commands ###
