"""add_dates_to_sessions_and_rows

Revision ID: 3a147c56b630
Revises: a372028e6003
Create Date: 2026-05-22 00:55:18.495337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a147c56b630'
down_revision: Union[str, None] = 'a372028e6003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_sessions', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('timetable_rows', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('timetable_rows', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_rows', 'end_date')
    op.drop_column('timetable_rows', 'start_date')
    op.drop_column('scheduling_sessions', 'start_date')
    # ### end Alembic commands ###
