"""rename_class_to_batch_semester_subjects

Revision ID: 3be9a23b6c85
Revises: c5ee036b0c50
Create Date: 2026-04-15 00:20:23.679557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be9a23b6c85'
down_revision: Union[str, None] = 'c5ee036b0c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_semester_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_code', sa.String(length=20), nullable=False),
    sa.Column('batch_code', sa.String(length=10), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_semester_subjects_batch_code'), 'batch_semester_subjects', ['batch_code'], unique=False)
    op.create_index(op.f('ix_batch_semester_subjects_id'), 'batch_semester_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_batch_semester_subjects_major_code'), 'batch_semester_subjects', ['major_code'], unique=False)
    op.drop_index('ix_class_semester_subjects_class_code', table_name='class_semester_subjects')
    op.drop_index('ix_class_semester_subjects_id', table_name='class_semester_subjects')
    op.drop_table('class_semester_subjects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_semester_subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('semester_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='class_semester_subjects_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='class_semester_subjects_pkey')
    )
    op.create_index('ix_class_semester_subjects_id', 'class_semester_subjects', ['id'], unique=False)
    op.create_index('ix_class_semester_subjects_class_code', 'class_semester_subjects', ['class_code'], unique=False)
    op.drop_index(op.f('ix_batch_semester_subjects_major_code'), table_name='batch_semester_subjects')
    op.drop_index(op.f('ix_batch_semester_subjects_id'), table_name='batch_semester_subjects')
    op.drop_index(op.f('ix_batch_semester_subjects_batch_code'), table_name='batch_semester_subjects')
    op.drop_table('batch_semester_subjects')
    # ### end Alembic commands ###
