"""init_db

Revision ID: 4756fc6e7d07
Revises: 
Create Date: 2026-04-08 19:03:08.990383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4756fc6e7d07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('major_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_classes_class_id'), 'classes', ['class_id'], unique=False)
    op.create_table('semesters',
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('semester_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='semesterstatusenum'), nullable=True),
    sa.PrimaryKeyConstraint('semester_id')
    )
    op.create_index(op.f('ix_semesters_semester_id'), 'semesters', ['semester_id'], unique=False)
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('theory_hours', sa.Integer(), nullable=True),
    sa.Column('practice_hours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_code')
    )
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SCHEDULER', 'LECTURER', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('equivalent_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_subject_id', sa.Integer(), nullable=False),
    sa.Column('equivalent_subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equivalent_subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['original_subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equivalent_subjects_id'), 'equivalent_subjects', ['id'], unique=False)
    op.create_table('lecturers',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('lecturer_code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('FULL_TIME', 'VISITING', name='lecturertypeenum'), nullable=True),
    sa.Column('max_quota', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lecturer_id'),
    sa.UniqueConstraint('lecturer_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_lecturers_lecturer_id'), 'lecturers', ['lecturer_id'], unique=False)
    op.create_table('lecturer_registrations',
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_main_lecturer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.lecturer_id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_index(op.f('ix_lecturer_registrations_registration_id'), 'lecturer_registrations', ['registration_id'], unique=False)
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('lecturer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', name='schedulestatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.lecturer_id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedules_schedule_id'), 'schedules', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_schedule_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_lecturer_registrations_registration_id'), table_name='lecturer_registrations')
    op.drop_table('lecturer_registrations')
    op.drop_index(op.f('ix_lecturers_lecturer_id'), table_name='lecturers')
    op.drop_table('lecturers')
    op.drop_index(op.f('ix_equivalent_subjects_id'), table_name='equivalent_subjects')
    op.drop_table('equivalent_subjects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_semesters_semester_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_classes_class_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
