"""update_registration_list_ondelete

Revision ID: 4e5fc643b5f5
Revises: 3a147c56b630
Create Date: 2026-05-22 02:15:46.266004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5fc643b5f5'
down_revision: Union[str, None] = '3a147c56b630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scheduling_sessions_registration_list_id_fkey', 'scheduling_sessions', type_='foreignkey')
    op.create_foreign_key('scheduling_sessions_registration_list_id_fkey', 'scheduling_sessions', 'registration_lists', ['registration_list_id'], ['list_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scheduling_sessions_registration_list_id_fkey', 'scheduling_sessions', type_='foreignkey')
    op.create_foreign_key('scheduling_sessions_registration_list_id_fkey', 'scheduling_sessions', 'registration_lists', ['registration_list_id'], ['list_id'])
    # ### end Alembic commands ###
