"""Redesign curriculum model to TrainingProgram

Revision ID: 59d54d862d2b
Revises: b141ba300237
Create Date: 2026-04-18 03:07:44.699508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d54d862d2b'
down_revision: Union[str, None] = 'b141ba300237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department_major', sa.String(length=50), nullable=True),
    sa.Column('batch', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_programs_id'), 'training_programs', ['id'], unique=False)
    op.create_index(op.f('ix_training_programs_program_code'), 'training_programs', ['program_code'], unique=True)
    op.create_table('program_curriculums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['training_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_curriculums_id'), 'program_curriculums', ['id'], unique=False)
    op.drop_index('ix_batch_semester_subjects_batch_code', table_name='batch_semester_subjects')
    op.drop_index('ix_batch_semester_subjects_id', table_name='batch_semester_subjects')
    op.drop_index('ix_batch_semester_subjects_major_code', table_name='batch_semester_subjects')
    op.drop_table('batch_semester_subjects')
    op.drop_index('ix_major_subjects_id', table_name='major_subjects')
    op.drop_index('ix_major_subjects_major_code', table_name='major_subjects')
    op.drop_table('major_subjects')
    op.add_column('classes', sa.Column('program_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'training_programs', ['program_id'], ['id'], ondelete='SET NULL')
    op.drop_column('classes', 'major_id')
    op.add_column('session_entries', sa.Column('program_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'session_entries', 'training_programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_entries', 'batch_code')
    op.drop_column('session_entries', 'major_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_entries', sa.Column('major_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('session_entries', sa.Column('batch_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session_entries', type_='foreignkey')
    op.drop_column('session_entries', 'program_id')
    op.add_column('classes', sa.Column('major_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'program_id')
    op.create_table('major_subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('major_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='major_subjects_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='major_subjects_pkey')
    )
    op.create_index('ix_major_subjects_major_code', 'major_subjects', ['major_code'], unique=False)
    op.create_index('ix_major_subjects_id', 'major_subjects', ['id'], unique=False)
    op.create_table('batch_semester_subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('major_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('batch_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('semester_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='batch_semester_subjects_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='batch_semester_subjects_pkey')
    )
    op.create_index('ix_batch_semester_subjects_major_code', 'batch_semester_subjects', ['major_code'], unique=False)
    op.create_index('ix_batch_semester_subjects_id', 'batch_semester_subjects', ['id'], unique=False)
    op.create_index('ix_batch_semester_subjects_batch_code', 'batch_semester_subjects', ['batch_code'], unique=False)
    op.drop_index(op.f('ix_program_curriculums_id'), table_name='program_curriculums')
    op.drop_table('program_curriculums')
    op.drop_index(op.f('ix_training_programs_program_code'), table_name='training_programs')
    op.drop_index(op.f('ix_training_programs_id'), table_name='training_programs')
    op.drop_table('training_programs')
    # ### end Alembic commands ###
