"""make_email_nullable_and_add_receive_emails

Revision ID: 5dc409c28bcc
Revises: 6770dd9a346c
Create Date: 2026-05-22 03:26:33.188795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc409c28bcc'
down_revision: Union[str, None] = '6770dd9a346c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('receive_emails', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'receive_emails')
    # ### end Alembic commands ###
