"""Add RegistrationList

Revision ID: 8a7a05ba5484
Revises: 4756fc6e7d07
Create Date: 2026-04-13 20:45:28.727815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7a05ba5484'
down_revision: Union[str, None] = '4756fc6e7d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_lists',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=200), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.create_index(op.f('ix_registration_lists_list_id'), 'registration_lists', ['list_id'], unique=False)
    op.add_column('lecturer_registrations', sa.Column('list_id', sa.Integer(), nullable=False))
    op.drop_constraint('lecturer_registrations_semester_id_fkey', 'lecturer_registrations', type_='foreignkey')
    op.create_foreign_key(None, 'lecturer_registrations', 'registration_lists', ['list_id'], ['list_id'], ondelete='CASCADE')
    op.drop_column('lecturer_registrations', 'semester_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer_registrations', sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lecturer_registrations', type_='foreignkey')
    op.create_foreign_key('lecturer_registrations_semester_id_fkey', 'lecturer_registrations', 'semesters', ['semester_id'], ['semester_id'])
    op.drop_column('lecturer_registrations', 'list_id')
    op.drop_index(op.f('ix_registration_lists_list_id'), table_name='registration_lists')
    op.drop_table('registration_lists')
    # ### end Alembic commands ###
