"""add_description_to_scheduling_session

Revision ID: 91b03dbb4837
Revises: 4e5fc643b5f5
Create Date: 2026-05-22 02:21:24.850240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b03dbb4837'
down_revision: Union[str, None] = '4e5fc643b5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_sessions', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduling_sessions', 'description')
    # ### end Alembic commands ###
