"""add_is_open_and_list_subjects

Revision ID: a372028e6003
Revises: 54549aadce74
Create Date: 2026-05-11 22:47:47.208887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a372028e6003'
down_revision: Union[str, None] = '54549aadce74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_list_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['registration_lists.list_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_list_subjects_id'), 'registration_list_subjects', ['id'], unique=False)
    op.add_column('registration_lists', sa.Column('is_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_lists', 'is_open')
    op.drop_index(op.f('ix_registration_list_subjects_id'), table_name='registration_list_subjects')
    op.drop_table('registration_list_subjects')
    # ### end Alembic commands ###
