"""Add department_major and batch to Class

Revision ID: ab6687639379
Revises: 59d54d862d2b
Create Date: 2026-04-18 03:36:22.856193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6687639379'
down_revision: Union[str, None] = '59d54d862d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('department_major', sa.String(length=50), nullable=True))
    op.add_column('classes', sa.Column('batch', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_classes_batch'), 'classes', ['batch'], unique=False)
    op.create_index(op.f('ix_classes_department_major'), 'classes', ['department_major'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_department_major'), table_name='classes')
    op.drop_index(op.f('ix_classes_batch'), table_name='classes')
    op.drop_column('classes', 'batch')
    op.drop_column('classes', 'department_major')
    # ### end Alembic commands ###
