"""Add theory and practice credits to subjects

Revision ID: b141ba300237
Revises: 222d5fccf47d
Create Date: 2026-04-18 02:00:44.848465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b141ba300237'
down_revision: Union[str, None] = '222d5fccf47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('theory_credits', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('practice_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'practice_credits')
    op.drop_column('subjects', 'theory_credits')
    # ### end Alembic commands ###
