"""add_major_subjects_and_class_semester_subjects

Revision ID: c5ee036b0c50
Revises: 0c793f62dca1
Create Date: 2026-04-14 23:59:31.259780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ee036b0c50'
down_revision: Union[str, None] = '0c793f62dca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_semester_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.String(length=20), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_semester_subjects_class_code'), 'class_semester_subjects', ['class_code'], unique=False)
    op.create_index(op.f('ix_class_semester_subjects_id'), 'class_semester_subjects', ['id'], unique=False)
    op.create_table('major_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_code', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_subjects_id'), 'major_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_major_subjects_major_code'), 'major_subjects', ['major_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_major_subjects_major_code'), table_name='major_subjects')
    op.drop_index(op.f('ix_major_subjects_id'), table_name='major_subjects')
    op.drop_table('major_subjects')
    op.drop_index(op.f('ix_class_semester_subjects_id'), table_name='class_semester_subjects')
    op.drop_index(op.f('ix_class_semester_subjects_class_code'), table_name='class_semester_subjects')
    op.drop_table('class_semester_subjects')
    # ### end Alembic commands ###
