"""add_lecturer_position

Revision ID: dde90543f6f2
Revises: ab6687639379
Create Date: 2026-04-23 12:25:48.868380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde90543f6f2'
down_revision: Union[str, None] = 'ab6687639379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturers', sa.Column('position', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturers', 'position')
    # ### end Alembic commands ###
